from pydantic import BaseModel, Field

from src.domain.models.pipeline_result import PipelineResult


class FindingSummaryDTO(BaseModel):
    """Structured DTO for a single top operational finding in the API response."""

    campaign_name: str = Field(description="Campaign name where the anomaly was detected")
    platform: str = Field(description="Advertising platform (google_ads, meta_ads)")
    country: str = Field(description="ISO country code of the campaign")
    metric_change: str = Field(
        description="Human-readable metric delta, e.g. 'Conversions: 140 → 0 (-100%)'"
    )
    issue_type: str = Field(
        description="Root-cause label (VERİ / TRACKING HATASI vs PERFORMANS SORUNU)"
    )
    operational_action: str = Field(
        description="Concrete, non-generic operational action step in Turkish"
    )
    severity: str = Field(description="Severity level (CRITICAL, HIGH, MEDIUM, LOW)")
    score: float = Field(description="Computed operational severity score")


class PipelineResponse(BaseModel):
    """Data Transfer Object representing the output summary of a pipeline execution."""

    execution_id: str = Field(description="Unique UUID identifying the execution run")
    status: str = Field(description="Execution status (e.g. success, partial_success, failed)")
    anomalies_count: int = Field(description="Number of anomalies detected during the run")
    critical_count: int = Field(
        default=0,
        description="Number of critical severity anomalies detected during the run",
    )
    duration_seconds: float = Field(
        default=0.0,
        description="Total pipeline run execution duration in seconds",
    )
    output_files: dict[str, str] = Field(
        default_factory=dict,
        description="Map of output file keys to filesystem paths",
    )
    briefing_summary: str = Field(
        default="", description="Executive summary generated by LLM or fallback"
    )
    top_anomalies: list[str] = Field(
        default_factory=list, description="Top critical anomalies detected during run"
    )
    recommended_actions: list[str] = Field(
        default_factory=list, description="Recommended operational mitigation actions"
    )
    top_3_findings: list[FindingSummaryDTO] = Field(
        default_factory=list,
        description="Top 3 ranked findings with root-cause analysis and actions",
    )
    message: str = Field(
        default="Pipeline execution completed",
        description="Human-readable execution status message",
    )
    execution_time_seconds: float = Field(
        default=0.0,
        description="Legacy alias for duration_seconds",
    )
    output_paths: dict[str, str] = Field(
        default_factory=dict,
        description="Legacy alias for output_files",
    )

    def model_post_init(self, __context: object) -> None:
        """Ensure execution_time_seconds and output_paths match duration_seconds."""
        if self.duration_seconds != 0.0 and self.execution_time_seconds == 0.0:
            self.execution_time_seconds = self.duration_seconds
        elif self.execution_time_seconds != 0.0 and self.duration_seconds == 0.0:
            self.duration_seconds = self.execution_time_seconds

        if self.output_files and not self.output_paths:
            self.output_paths = self.output_files
        elif self.output_paths and not self.output_files:
            self.output_files = self.output_paths

    @classmethod
    def from_domain(cls, result: PipelineResult) -> "PipelineResponse":
        """Constructs a PipelineResponse DTO from a domain PipelineResult entity."""
        findings_dtos: list[FindingSummaryDTO] = []
        for finding_dict in result.top_3_findings:
            findings_dtos.append(
                FindingSummaryDTO(
                    campaign_name=finding_dict.get("campaign_name", ""),
                    platform=finding_dict.get("platform", ""),
                    country=finding_dict.get("country", ""),
                    metric_change=finding_dict.get("metric_change", ""),
                    issue_type=finding_dict.get("issue_type", ""),
                    operational_action=finding_dict.get("operational_action", ""),
                    severity=finding_dict.get("severity", ""),
                    score=float(finding_dict.get("score", "0")),
                )
            )

        return cls(
            execution_id=result.execution_id,
            status=result.status,
            anomalies_count=result.anomalies_count,
            critical_count=result.critical_count,
            duration_seconds=result.duration_seconds,
            briefing_summary=result.briefing_summary,
            top_anomalies=result.top_anomalies,
            recommended_actions=result.recommended_actions,
            top_3_findings=findings_dtos,
            output_files=result.output_files,
            execution_time_seconds=result.duration_seconds,
            output_paths=result.output_files,
            message=f"Pipeline execution finished with status: {result.status}",
        )
