"""Pydantic v2 data contracts for Gemini agent typed reasoning and diagnosis."""

from pydantic import BaseModel, ConfigDict, Field


class Hypothesis(BaseModel):
    """Represents a single competing hypothesis evaluated against evidence."""

    model_config = ConfigDict(frozen=True)

    statement: str = Field(
        description="Hypothesis description e.g. 'Meta CAPI / Pixel event tracking breakdown'"
    )
    supporting_evidence: list[str] = Field(
        default_factory=list,
        description="Evidence items from the dossier supporting this hypothesis",
    )
    contradictory_evidence: list[str] = Field(
        default_factory=list,
        description="Evidence items contradicting this hypothesis",
    )
    confidence: float = Field(
        ge=0.0,
        le=1.0,
        description="Confidence score between 0.0 and 1.0 based on evidence strength",
    )
    missing_evidence: list[str] = Field(
        default_factory=list,
        description="Missing data needed for 100% certainty",
    )


class OperationalActionPlan(BaseModel):
    """Represents concrete operational actions across budget, bid, creative, and tracking."""

    model_config = ConfigDict(frozen=True)

    budget_action: str = Field(
        description="Budget action e.g. 'HOLD_CURRENT_BUDGET' or 'REDUCE_BUDGET_20_PERCENT'"
    )
    bid_action: str = Field(
        description="Bid strategy action e.g. 'NO_CHANGE' or 'CAP_TARGET_CPA_AT_BASELINE'"
    )
    creative_action: str = Field(
        description="Creative/landing page action e.g. 'ROTATE_FATIGUED_VIDEO_CREATIVES'"
    )
    tracking_action: str = Field(
        description="Tracking diagnostic action e.g. 'VERIFY_EVENT_MANAGER_PURCHASE_PIXEL_CAPI'"
    )
    rationale: str = Field(description="Data-driven rationale for the prescribed action plan")
    concrete_steps: list[str] = Field(
        default_factory=list,
        description="Step-by-step concrete instructions for performance marketer",
    )
    expected_effect: str = Field(description="Expected financial or efficiency outcome")
    risk_level: str = Field(description="Risk level of the action e.g. 'LOW', 'MEDIUM', 'HIGH'")
    requires_approval: bool = Field(
        description="Whether human manager approval is required before execution"
    )


class DiagnosedFinding(BaseModel):
    """Represents a complete root-cause analysis and action plan for a single campaign finding."""

    model_config = ConfigDict(frozen=True)

    campaign_name: str = Field(description="Name of the campaign analyzed")
    platform: str = Field(description="Advertising platform name e.g. 'google_ads' or 'meta_ads'")
    country: str = Field(description="ISO country code e.g. 'US' or 'DE'")
    issue_type: str = Field(
        description="Root cause classification: 'DATA_QUALITY', 'PERFORMANCE', or 'MIXED'"
    )
    confidence_score: float = Field(
        ge=0.0,
        le=1.0,
        description="Overall confidence score for the diagnosis between 0.0 and 1.0",
    )
    root_cause_analysis: str = Field(
        description="Detailed metric-correlation based root cause diagnosis narrative"
    )
    competing_hypotheses: list[Hypothesis] = Field(
        default_factory=list,
        description="List of competing hypotheses evaluated",
    )
    selected_hypothesis: Hypothesis = Field(
        description="The primary hypothesis selected based on evidence"
    )
    action_plan: OperationalActionPlan = Field(
        description="Channel-specific operational action plan"
    )
    metric_change_summary: str = Field(
        description="Human-readable delta summary of deviating metrics vs baseline"
    )
    business_impact_narrative: str = Field(
        description="Executive narrative on company profitability and budget impact"
    )


class BatchAnalysisResult(BaseModel):
    """Top-level structured output contract generated by Gemini agent for batch execution."""

    model_config = ConfigDict(frozen=True)

    findings: list[DiagnosedFinding] = Field(
        default_factory=list,
        description="Top campaign findings analyzed with root cause and action plans",
    )
    executive_summary: str = Field(
        description="1-2 paragraph morning executive summary briefing in Turkish for C-Level"
    )
    overall_data_health: str = Field(
        description="Overall dataset health status: 'HEALTHY', 'DEGRADED', or 'CRITICAL'"
    )
    analysis_timestamp: str = Field(description="ISO timestamp string of analysis execution")
